const products = [
	{
		id: 1,
		name: 'Shoes puma',
		price: 4999,
		image: 'shoes-1.jpg',
		qty: 1,
		brand: 'Puma',
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 2,
		name: 'T-Sirt Stylish',
		price: 249,
		image: 'tsirt-2.png',
		qty: 1,
		brand: 'Best T-Sirt',
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 3,
		name: 'T-Sirt lofer',
		price: 599,
		image: 'tsirt-1.png',
		qty: 1,
		brand: 'Nike',
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 4,
		name: 'Glasses',
		price: 229,
		image: 'glasses-1.jpg',
		qty: 1,
		brand: 'Oxydo Eyeglasses',
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 5,
		name: 'T-sirt3',
		price: 339,
		image: 'tsirt-3.jpg',
		qty: 1,
		brand: "Levi's",
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 6,
		name: 'Dhasu T-Sirt',
		price: 259,
		image: 't-sirt1.webp',
		qty: 1,
		brand: 'Arrow',
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 7,
		name: 'Glass',
		price: 149,
		image: 'glasses-3.jpg',
		qty: 1,
		brand: 'Ray Ban Eyeglasses',
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 8,
		name: 'Jeans',
		price: 1499,
		image: 'jeans.webp',
		qty: 1,
		brand: 'Lee Cooper',
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 9,
		name: 'Shoes Bta',
		price: 1999,
		image: 'shoes.webp',
		qty: 1,
		brand: 'BATA',
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 10,
		name: 'Sirt',
		price: 799,
		image: 'sirt.png',
		qty: 1,
		brand: 'Indian Terrain',
		category: 'man',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 11,
		name: 'Clothes - 1',
		price: 4999,
		image: 'women-1.png',
		qty: 1,
		brand: 'Puma',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing     .',
	},
	{
		id: 12,
		name: 'Clothes - 1',
		price: 249,
		image: 'women-2.jpg',
		qty: 1,
		brand: 'Best T-Sirt',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing ',
	},
	{
		id: 13,
		name: 'Clothes - 1',
		price: 599,
		image: 'women-3.jpg',
		qty: 1,
		brand: 'Nike',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 14,
		name: 'Clothes - 1',
		price: 229,
		image: 'women-4.jpg',
		qty: 1,
		brand: 'Oxydo Eyeglasses',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 15,
		name: 'Clothes - 1',
		price: 339,
		image: 'women-5.webp',
		qty: 1,
		brand: "Levi's",
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 16,
		name: 'Clothes - 1',
		price: 259,
		image: 'women-6.jpeg',
		qty: 1,
		brand: 'Arrow',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 17,
		name: 'Clothes - 1',
		price: 149,
		image: 'women-7.jpg',
		qty: 1,
		brand: 'Ray Ban Eyeglasses',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 18,
		name: 'Clothes - 1',
		price: 1499,
		image: 'women-8.webp',
		qty: 1,
		brand: 'Lee Cooper',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 19,
		name: 'Clothes - 1',
		price: 1999,
		image: 'women-9.jpg',
		qty: 1,
		brand: 'BATA',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 20,
		name: 'Clothes - 1',
		price: 2499,
		image: 'women-11.png',
		qty: 1,
		brand: 'The Casio Whiz',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 21,
		name: 'Clothes - 1',
		price: 49,
		image: 'women-12.webp',
		qty: 1,
		brand: 'LOS POLISTAS',
		category: 'women',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},

	{
		id: 22,
		name: 'Shoes pum',
		price: 4999,
		image: 'kids-1.png',
		qty: 1,
		brand: 'Puma',
		category: 'kids',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 23,
		name: 'T-Sirt Stylish',
		price: 249,
		image: 'kids-2.png',
		qty: 1,
		brand: 'Best T-Sirt',
		category: 'kids',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 24,
		name: 'T-Sirt lofer',
		price: 599,
		image: 'kids-3.png',
		qty: 1,
		brand: 'Nike',
		category: 'kids',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 25,
		name: 'Glasses',
		price: 229,
		image: 'kids-4.png',
		qty: 1,
		brand: 'Oxydo Eyeglasses',
		category: 'kids',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 26,
		name: 'T-sirt3',
		price: 339,
		image: 'kids-5.png',
		qty: 1,
		brand: "Levi's",
		category: 'kids',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 27,
		name: 'Dhasu T-Sirt',
		price: 259,
		image: 't-sirt1.webp',
		qty: 1,
		brand: 'Arrow',
		category: 'kids',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 28,
		name: 'Glass',
		price: 149,
		image: 'glasses-3.jpg',
		qty: 1,
		brand: 'Ray Ban Eyeglasses',
		category: 'kids',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
	{
		id: 29,
		name: 'Jeans',
		price: 1499,
		image: 'jeans.webp',
		qty: 1,
		brand: 'Lee Cooper',
		category: 'kids',
		description: 'Lorem, ipsum dolor sit amet consectetur adipisicing   ',
	},
];

export default products;
